import { useState } from "react";
import { getPack } from "@/src/lib/pack";
import { useProgress } from "@/src/lib/progress";
import { COMMIT } from "@/src/lib/evidence";
import { GhostButton, ScreenHeader, SecondaryButton, StatusIndicator, Tag } from "@/src/components/ui";

const pack = getPack();

const PACK_FILES = [
  ["overview.json", pack.overview.meta],
  ["architecture.json", pack.architecture.meta],
  ["workflows.json", pack.workflows.meta],
  ["reading-order.json", pack.readingOrder.meta],
  ["quiz.json", pack.quiz.meta],
  ["tasks.json", pack.tasks.meta],
] as const;

export default function SettingsScreen() {
  const { milestones, readiness, reset } = useProgress();
  const [confirming, setConfirming] = useState(false);

  return (
    <div className="settings">
      <ScreenHeader eyebrow="Settings" title="Session & data" />

      <section className="settings-card">
        <h2 className="section-title">Your progress</h2>
        <p className="dim">Stored locally in this browser. Nothing is sent anywhere.</p>
        <ul className="settings-milestones">
          {milestones.map((m) => (
            <li key={m.id}>
              <StatusIndicator status={m.status} size={18} />
              <span>{m.label}</span>
              <span className="dim">{m.detail}</span>
            </li>
          ))}
        </ul>
        <p>
          Understanding: <strong className="mono">{readiness.totalScore}%</strong>
        </p>
        <div className="settings-danger">
          {confirming ? (
            <>
              <span className="tone-risk">! This clears reading, answers, traced workflows and task progress.</span>
              <SecondaryButton
                size="sm"
                className="btn--danger"
                onClick={() => {
                  reset();
                  setConfirming(false);
                }}
              >
                Yes, reset progress
              </SecondaryButton>
              <GhostButton onClick={() => setConfirming(false)}>Cancel</GhostButton>
            </>
          ) : (
            <SecondaryButton size="sm" onClick={() => setConfirming(true)}>
              Reset progress…
            </SecondaryButton>
          )}
        </div>
      </section>

      <section className="settings-card">
        <h2 className="section-title">Onboarding pack</h2>
        <p className="dim">
          Repository commit <code>{COMMIT}</code>
        </p>
        <table className="pack-table">
          <thead>
            <tr>
              <th scope="col">File</th>
              <th scope="col">Generated by</th>
              <th scope="col">Commit</th>
              <th scope="col">Data</th>
            </tr>
          </thead>
          <tbody>
            {PACK_FILES.map(([name, meta]) => (
              <tr key={name}>
                <td>
                  <code>{name}</code>
                </td>
                <td>{meta.generatedBy.member}</td>
                <td>
                  {meta.repoCommit === COMMIT ? (
                    <Tag tone="verified">MATCHES</Tag>
                  ) : (
                    <Tag tone="risk">MISMATCH</Tag>
                  )}
                </td>
                <td>{meta.mock ? <Tag tone="risk">MOCK</Tag> : <Tag tone="verified">REAL</Tag>}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <section className="settings-card">
        <h2 className="section-title">Keyboard</h2>
        <dl className="shortcuts">
          <div>
            <dt>
              <kbd>Ctrl</kbd> <kbd>K</kbd>
            </dt>
            <dd>Search files, claims, workflows and reading steps</dd>
          </div>
          <div>
            <dt>
              <kbd>↑</kbd> <kbd>↓</kbd>
            </dt>
            <dd>Move between workflow steps</dd>
          </div>
          <div>
            <dt>
              <kbd>Esc</kbd>
            </dt>
            <dd>Close the evidence panel or search</dd>
          </div>
        </dl>
      </section>
    </div>
  );
}
